# Generated by Django 4.0.5 on 2022-09-01 04:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergySourceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_source', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('co2_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nh3_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('co_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('no_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('no2_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('o3_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pm_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('so2_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.countries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Grains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_size', models.FloatField()),
                ('max_size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Residuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('operating_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24)])),
                ('json_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.countries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('energy_consumption', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('energy_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.energysourcetypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
