# Generated by Django 4.0.6 on 2022-07-14 14:29

from django.db import migrations

import os
import pandas as pd

from ..models import EnergySourceTypes
from ..models import Countries

def populate(*ags, **kwargs):

    df = pd.read_csv(os.path.join('static', 'Country.csv'))
    for val in df['Country']:
        Countries.objects.get_or_create(country = val)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate,)
    ]
