# Generated by Django 4.0.5 on 2022-09-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_energysourcetypes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energysourcetypes',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
